# Generated by Django 3.2.9 on 2022-04-18 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_gkp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_date', models.DateTimeField(auto_now=True)),
                ('gas_last', models.IntegerField()),
                ('gas_new', models.IntegerField()),
                ('gas_tarif', models.FloatField()),
                ('gas_suma', models.FloatField()),
                ('gas_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
