# Generated by Django 3.2.8 on 2022-04-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_gkp', '0002_gas_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas_table',
            name='gas_period_end',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gas_table',
            name='gas_period_start',
            field=models.DateField(auto_now=True),
        ),
    ]
