# Generated by Django 3.2.8 on 2022-04-18 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_gkp', '0004_alter_gas_table_gas_period_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gas_table',
            name='gas_period_end',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
