# Generated by Django 3.2.9 on 2022-04-21 14:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_gkp', '0005_alter_gas_table_gas_period_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Res_1_zona_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_date', models.DateTimeField(auto_now=True)),
                ('res_period_start', models.DateField(default=datetime.date.today)),
                ('res_period_end', models.DateField(default=datetime.date.today)),
                ('res_last', models.IntegerField()),
                ('res_new', models.IntegerField()),
                ('res_tarif', models.FloatField()),
                ('res_suma', models.FloatField()),
                ('res_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
