# Generated by Django 3.2.9 on 2022-04-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_gkp', '0006_res_1_zona_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas_table',
            name='gas_rezult',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='res_1_zona_table',
            name='res_rezult',
            field=models.IntegerField(default=0),
        ),
    ]
