# Generated by Django 3.2.9 on 2022-05-02 07:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_gkp', '0009_res_3_zona_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Water_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_date', models.DateTimeField(auto_now=True)),
                ('water_period_start', models.DateField(default=datetime.date.today)),
                ('water_period_end', models.DateField(default=datetime.date.today)),
                ('water_last', models.IntegerField()),
                ('water_new', models.IntegerField()),
                ('water_rezult', models.IntegerField(default=0)),
                ('water_tarif', models.FloatField()),
                ('water_abonplata', models.FloatField()),
                ('water_suma', models.FloatField()),
                ('water_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
